# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationmetainfo',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='publicationmetainfo',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
