# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-22 16:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationmetainfo',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_publications', to=settings.AUTH_USER_MODEL),
        ),
    ]
