# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-22 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_auto_20170522_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationmetainfo',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
