# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_publicationmetainfo_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationmetainfo',
            name='publication_type',
            field=models.CharField(default='achievement', max_length=30),
            preserve_default=False,
        ),
    ]
